services:
  stash-manager:
    image: stash-manager
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stash-manager
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      - TZ=America/Chicago
      - FLASK_RUN_PORT=5001
    env_file: .env
    volumes:
      # - ${CONFIG_PATH:-/mnt/user/appdata/stash-manager/config}:/config
      - ./config:/config
      - ./data:/data
      # - ${MEDIA_PATH:-./media}:/media  # Not used by application
      # Logs will be stored in config/logs directory